name = "dste-api"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# 生产环境自定义域名，绕开服务器对 workers.dev 的 DNS 污染 + SNI 阻断
[[routes]]
pattern = "api.dste.jasonxspace.cc"
custom_domain = true
zone_id = "0ef3689c540f72658247ce306882d790"

[[kv_namespaces]]
binding = "DSTE_KV"
id = "69ed6153435d4ba5b3b17c9077ce74c9"
